onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@tailwindcss/oxide'
  - msw
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
