// English sentiment lexicon, hand-curated for short YouTube comment text.
// Valences in {-2, -1, +1, +2}. Lowercase only. Single bag-of-words lookup.
// Bias: emotion / opinion words, not topic words. Keep false-positive risk low.

export const LEXICON_EN: Readonly<Record<string, number>> = {
  // Strong positive (+2)
  amazing: 2, awesome: 2, brilliant: 2, excellent: 2, fantastic: 2,
  flawless: 2, genius: 2, glorious: 2, gorgeous: 2, incredible: 2,
  legendary: 2, magnificent: 2, marvelous: 2, masterpiece: 2, outstanding: 2,
  perfect: 2, phenomenal: 2, spectacular: 2, stellar: 2, stunning: 2,
  sublime: 2, superb: 2, terrific: 2, unbelievable: 2, wonderful: 2,
  best: 2, beautiful: 2, breathtaking: 2, ecstatic: 2, exceptional: 2,
  unmatched: 2, unreal: 2, unrivaled: 2, transcendent: 2, riveting: 2,
  goated: 2, fire: 2, slaps: 2, banger: 2, peak: 2,
  iconic: 2, hilarious: 2, hysterical: 2, inspiring: 2, inspirational: 2,
  refreshing: 2, revolutionary: 2, mindblowing: 2, masterclass: 2,
  godlike: 2, immaculate: 2, exquisite: 2,

  // Moderate positive (+1)
  good: 1, great: 1, nice: 1, cool: 1, sweet: 1, lovely: 1,
  pleasant: 1, enjoyable: 1, fun: 1, funny: 1, entertaining: 1,
  interesting: 1, intriguing: 1, smart: 1, clever: 1, helpful: 1,
  useful: 1, solid: 1, decent: 1, satisfying: 1, satisfied: 1,
  happy: 1, glad: 1, grateful: 1, thankful: 1, thanks: 1,
  appreciate: 1, appreciated: 1, love: 1, loved: 1, like: 1, liked: 1,
  enjoy: 1, enjoyed: 1, win: 1, winning: 1, won: 1, success: 1,
  successful: 1, achievement: 1, achieve: 1, progress: 1, improve: 1,
  improved: 1, improving: 1, better: 1, recommend: 1, recommended: 1,
  approve: 1, approved: 1, accurate: 1, correct: 1, right: 1,
  truthful: 1, honest: 1, brave: 1, courageous: 1,
  positive: 1, optimistic: 1, hopeful: 1, kind: 1, gentle: 1,
  warm: 1, friendly: 1, polite: 1, respectful: 1, respect: 1,
  legend: 1, hero: 1, talented: 1, gifted: 1, skilled: 1,
  pro: 1, master: 1, expert: 1, polished: 1, smooth: 1,
  clean: 1, crisp: 1, sharp: 1, fresh: 1, dope: 1,
  rad: 1, lit: 1, neat: 1, cozy: 1,
  exciting: 1, excited: 1, eager: 1, thrilled: 1, ready: 1,
  recommendation: 1, easy: 1, simple: 1, original: 1, creative: 1,
  innovative: 1, fascinating: 1, captivating: 1, engaging: 1,
  delight: 1, delighted: 1, delightful: 1, joy: 1, joyful: 1,
  bless: 1, blessed: 1, blessing: 1, miracle: 1, wow: 1, yay: 1,
  yes: 1, yeah: 1, yep: 1, congrats: 1, congratulations: 1,
  bravo: 1, kudos: 1, props: 1, agree: 1, agreed: 1,
  cute: 1, adorable: 1, charming: 1,
  motivated: 1, motivating: 1, encouraging: 1, encouraged: 1, supportive: 1,
  comforting: 1, calming: 1, calm: 1, peaceful: 1, soothing: 1,
  // (note: `hopeful` and `calm` listed only once intentionally)

  // Moderate negative (-1)
  bad: -1, poor: -1, weak: -1, meh: -1, mediocre: -1,
  average: -1, dull: -1, lame: -1, cringe: -1, cringy: -1,
  cringey: -1, boring: -1, bored: -1, slow: -1, dry: -1,
  bland: -1, basic: -1, generic: -1, flat: -1, stale: -1,
  repetitive: -1, predictable: -1, cliche: -1, cliched: -1,
  overrated: -1, underwhelming: -1, disappointing: -1, disappointed: -1,
  frustrating: -1, frustrated: -1, annoying: -1, annoyed: -1,
  irritating: -1, irritated: -1, tedious: -1, exhausting: -1,
  confusing: -1, confused: -1, messy: -1, sloppy: -1, awkward: -1,
  uncomfortable: -1, weird: -1, strange: -1, odd: -1,
  problem: -1, issue: -1, bug: -1, broken: -1, broke: -1,
  fail: -1, failed: -1, failure: -1, lose: -1, lost: -1, losing: -1,
  loss: -1, mistake: -1, error: -1, wrong: -1,
  fake: -1, biased: -1, unfair: -1, lazy: -1, careless: -1,
  shallow: -1, cheap: -1, ugly: -1, plain: -1,
  forgettable: -1, dislike: -1, disliked: -1,
  ignore: -1, ignored: -1, skip: -1, skipped: -1,
  rude: -1, harsh: -1, distant: -1,
  selfish: -1, greedy: -1, arrogant: -1, condescending: -1, smug: -1,
  hypocritical: -1, hypocrite: -1, suspicious: -1, sketchy: -1,
  shady: -1, dishonest: -1, lying: -1, lied: -1, liar: -1,
  scam: -1, scammed: -1, fraud: -1, ripoff: -1, overpriced: -1,
  costly: -1, waste: -1, wasted: -1, wasteful: -1,
  pointless: -1, useless: -1, worthless: -1, irrelevant: -1, unnecessary: -1,
  outdated: -1, obsolete: -1, dated: -1,
  declining: -1, decline: -1, shrinking: -1, decreased: -1, decreasing: -1,
  sad: -1, sadly: -1, unfortunate: -1, unfortunately: -1, regret: -1,
  regretted: -1, sorry: -1, oops: -1, ugh: -1, sigh: -1,
  clickbait: -1, spam: -1, ads: -1, ad: -1, sponsored: -1, scammy: -1,

  // Strong negative (-2)
  terrible: -2, horrible: -2, awful: -2, atrocious: -2, appalling: -2,
  disgusting: -2, disgusted: -2, revolting: -2, repulsive: -2, vile: -2,
  garbage: -2, trash: -2, rubbish: -2, junk: -2,
  worst: -2, worse: -2, abysmal: -2, dreadful: -2, hideous: -2,
  pathetic: -2, ridiculous: -2, absurd: -2, insane: -2,
  stupid: -2, idiotic: -2, idiot: -2, moron: -2, dumb: -2,
  nightmare: -2, disaster: -2, catastrophe: -2, catastrophic: -2,
  devastating: -2, devastated: -2, painful: -2, agonizing: -2,
  unbearable: -2, intolerable: -2, infuriating: -2, infuriated: -2,
  enraged: -2, furious: -2, livid: -2, outrageous: -2, outraged: -2,
  scandalous: -2, evil: -2, wicked: -2, malicious: -2, cruel: -2,
  brutal: -2, savage: -2, ruthless: -2, heartless: -2, soulless: -2,
  toxic: -2, abusive: -2, abuser: -2, predator: -2, criminal: -2,
  illegal: -2, racist: -2, sexist: -2, homophobic: -2,
  hate: -2, hatred: -2, despise: -2, loathe: -2, abhor: -2,
  sucks: -2, sucked: -2, mid: -2, asshole: -2,
  loser: -2, clown: -2, propaganda: -2, brainwashed: -2, brainwash: -2,
  shameful: -2, embarrassing: -2, embarrassed: -2, humiliating: -2,
}

// Negation tokens. A polarity-bearing word within NEG_WINDOW tokens
// AFTER any of these has its sign flipped.
export const NEGATIONS_EN: ReadonlySet<string> = new Set([
  "not", "no", "never", "none", "nothing", "nobody", "nowhere", "neither",
  "nor", "without", "hardly", "barely", "scarcely",
  "doesn", "isn", "wasn", "shouldn", "wouldn", "couldn", "won", "don",
  "didn", "ain", "aren", "hasn", "haven", "hadn",
  "cannot", "cant", "dont", "wont", "isnt", "wasnt", "doesnt", "didnt",
  "couldnt", "wouldnt", "shouldnt", "havent", "hasnt", "hadnt", "arent",
])
